language: python
python:
  - "3.6"
env:
  -DJANGO=2.2.6 DB=sqlite3
before_install:
  - export DJANGO_SETTINGS_MODULE=MyFamilyTree.settings
install:
  - pip install -q Django==2.2.6
script:
  - pytest
